// Objective-C API for talking to github.com/probechain/go-probe/mobile Go package.
//   gobind -lang=objc github.com/probechain/go-probe/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Gprobe_H__
#define __Gprobe_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GprobeAccount;
@class GprobeAccounts;
@class GprobeAddress;
@class GprobeAddresses;
@class GprobeBigInt;
@class GprobeBigInts;
@class GprobeBinaries;
@class GprobeBlock;
@class GprobeBloom;
@class GprobeBools;
@class GprobeBoundContract;
@class GprobeCallMsg;
@class GprobeCallOpts;
@class GprobeContext;
@class GprobeDilithiumKeyInfo;
@class GprobeDilithiumKeyStore;
@class GprobeEnode;
@class GprobeEnodes;
@class GprobeFilterQuery;
@class GprobeHash;
@class GprobeHashes;
@class GprobeHeader;
@class GprobeHeaders;
@class GprobeInterface;
@class GprobeInterfaces;
@class GprobeKeyStore;
@class GprobeLog;
@class GprobeLogs;
@class GprobeMobileSigner;
@class GprobeNode;
@class GprobeNodeConfig;
@class GprobeNodeInfo;
@class GprobeNonce;
@class GprobePeerInfo;
@class GprobePeerInfos;
@class GprobeProbeumClient;
@class GprobeReceipt;
@class GprobeSmartLightNode;
@class GprobeSmartLightNodeConfig;
@class GprobeStrings;
@class GprobeSubscription;
@class GprobeSyncProgress;
@class GprobeTopics;
@class GprobeTransactOpts;
@class GprobeTransaction;
@class GprobeTransactions;
@protocol GprobeFilterLogsHandler;
@class GprobeFilterLogsHandler;
@protocol GprobeNewHeadHandler;
@class GprobeNewHeadHandler;
@protocol GprobeSigner;
@class GprobeSigner;

@protocol GprobeFilterLogsHandler <NSObject>
- (void)onError:(NSString* _Nullable)failure;
- (void)onFilterLogs:(GprobeLog* _Nullable)log;
@end

@protocol GprobeNewHeadHandler <NSObject>
- (void)onError:(NSString* _Nullable)failure;
- (void)onNewHead:(GprobeHeader* _Nullable)header;
@end

@protocol GprobeSigner <NSObject>
- (GprobeTransaction* _Nullable)sign:(GprobeAddress* _Nullable)addr unsignedTx:(GprobeTransaction* _Nullable)unsignedTx error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Account represents a stored key.
 */
@interface GprobeAccount : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetAddress retrieves the address associated with the account.
 */
- (GprobeAddress* _Nullable)getAddress;
/**
 * GetURL retrieves the canonical URL of the account.
 */
- (NSString* _Nonnull)getURL;
@end

/**
 * Accounts represents a slice of accounts.
 */
@interface GprobeAccounts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the account at the given index from the slice.
 */
- (GprobeAccount* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the account at the given index in the slice.
 */
- (BOOL)set:(long)index account:(GprobeAccount* _Nullable)account error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of accounts in the slice.
 */
- (long)size;
@end

/**
 * Address represents the 20 byte address of an ProbeChain account.
 */
@interface GprobeAddress : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewAddressFromBytes converts a slice of bytes to a hash value.
 */
- (nullable instancetype)initFromBytes:(NSData* _Nullable)binary;
/**
 * NewAddressFromHex converts a hex string to a address value.
 */
- (nullable instancetype)initFromHex:(NSString* _Nullable)hex;
/**
 * GetBytes retrieves the byte representation of the address.
 */
- (NSData* _Nullable)getBytes;
/**
 * GetHex retrieves the hex string representation of the address.
 */
- (NSString* _Nonnull)getHex;
/**
 * SetBytes sets the specified slice of bytes as the address value.
 */
- (BOOL)setBytes:(NSData* _Nullable)address error:(NSError* _Nullable* _Nullable)error;
/**
 * SetHex sets the specified hex string as the address value.
 */
- (BOOL)setHex:(NSString* _Nullable)address error:(NSError* _Nullable* _Nullable)error;
/**
 * String returns a printable representation of the address.
 */
- (NSString* _Nonnull)string;
@end

/**
 * Addresses represents a slice of addresses.
 */
@interface GprobeAddresses : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewAddresses creates a slice of uninitialized addresses.
 */
- (nullable instancetype)init:(long)size;
/**
 * NewAddressesEmpty creates an empty slice of Addresses values.
 */
- (nullable instancetype)initEmpty;
/**
 * Append adds a new address element to the end of the slice.
 */
- (void)append:(GprobeAddress* _Nullable)address;
/**
 * Get returns the address at the given index from the slice.
 */
- (GprobeAddress* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the address at the given index in the slice.
 */
- (BOOL)set:(long)index address:(GprobeAddress* _Nullable)address error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of addresses in the slice.
 */
- (long)size;
@end

/**
 * A BigInt represents a signed multi-precision integer.
 */
@interface GprobeBigInt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBigInt allocates and returns a new BigInt set to x.
 */
- (nullable instancetype)init:(int64_t)x;
/**
 * NewBigIntFromString allocates and returns a new BigInt set to x
interpreted in the provided base.
 */
- (nullable instancetype)initFromString:(NSString* _Nullable)x base:(long)base;
/**
 * GetBytes returns the absolute value of x as a big-endian byte slice.
 */
- (NSData* _Nullable)getBytes;
/**
 * GetInt64 returns the int64 representation of x. If x cannot be represented in
an int64, the result is undefined.
 */
- (int64_t)getInt64;
/**
 * GetString returns the value of x as a formatted string in some number base.
 */
- (NSString* _Nonnull)getString:(long)base;
/**
 * SetBytes interprets buf as the bytes of a big-endian unsigned integer and sets
the big int to that value.
 */
- (void)setBytes:(NSData* _Nullable)buf;
/**
 * SetInt64 sets the big int to x.
 */
- (void)setInt64:(int64_t)x;
/**
 * SetString sets the big int to x.

The string prefix determines the actual conversion base. A prefix of "0x" or
"0X" selects base 16; the "0" prefix selects base 8, and a "0b" or "0B" prefix
selects base 2. Otherwise the selected base is 10.
 */
- (void)setString:(NSString* _Nullable)x base:(long)base;
/**
 * Sign returns:

	-1 if x <  0
	 0 if x == 0
	+1 if x >  0
 */
- (long)sign;
/**
 * String returns the value of x as a formatted decimal string.
 */
- (NSString* _Nonnull)string;
@end

/**
 * BigInts represents a slice of big ints.
 */
@interface GprobeBigInts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBigInts creates a slice of uninitialized big numbers.
 */
- (nullable instancetype)init:(long)size;
/**
 * Get returns the bigint at the given index from the slice.
 */
- (GprobeBigInt* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the big int at the given index in the slice.
 */
- (BOOL)set:(long)index bigint:(GprobeBigInt* _Nullable)bigint error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of big ints in the slice.
 */
- (long)size;
@end

/**
 * Binaries represents a slice of byte slice
 */
@interface GprobeBinaries : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the byte slice at the given index from the slice.
 */
- (NSData* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the byte slice at the given index in the slice.
 */
- (BOOL)set:(long)index binary:(NSData* _Nullable)binary error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of byte slice in the slice.
 */
- (long)size;
/**
 * String implements the Stringer interface.
 */
- (NSString* _Nonnull)string;
@end

/**
 * Block represents an entire block in the ProbeChain blockchain.
 */
@interface GprobeBlock : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBlockFromJSON parses a block from a JSON data dump.
 */
- (nullable instancetype)initFromJSON:(NSString* _Nullable)data;
/**
 * NewBlockFromRLP parses a block from an RLP data dump.
 */
- (nullable instancetype)initFromRLP:(NSData* _Nullable)data;
/**
 * EncodeJSON encodes a block into a JSON data dump.
 */
- (NSString* _Nonnull)encodeJSON:(NSError* _Nullable* _Nullable)error;
/**
 * EncodeRLP encodes a block into an RLP data dump.
 */
- (NSData* _Nullable)encodeRLP:(NSError* _Nullable* _Nullable)error;
- (GprobeBloom* _Nullable)getBloom;
- (GprobeAddress* _Nullable)getCoinbase;
- (GprobeBigInt* _Nullable)getDifficulty;
- (NSData* _Nullable)getExtra;
- (int64_t)getGasLimit;
- (int64_t)getGasUsed;
- (GprobeHash* _Nullable)getHash;
- (GprobeHeader* _Nullable)getHeader;
- (GprobeHash* _Nullable)getMixDigest;
- (int64_t)getNonce;
- (int64_t)getNumber;
- (GprobeHash* _Nullable)getParentHash;
- (GprobeHash* _Nullable)getReceiptHash;
- (GprobeHash* _Nullable)getRoot;
- (int64_t)getTime;
- (GprobeTransaction* _Nullable)getTransaction:(GprobeHash* _Nullable)hash;
- (GprobeTransactions* _Nullable)getTransactions;
- (GprobeHash* _Nullable)getTxHash;
- (GprobeHash* _Nullable)getUncleHash;
- (GprobeHeaders* _Nullable)getUncles;
/**
 * String returns a printable representation of the block.
 */
- (NSString* _Nonnull)string;
@end

/**
 * Bloom represents a 256 bit bloom filter.
 */
@interface GprobeBloom : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetBytes retrieves the byte representation of the bloom filter.
 */
- (NSData* _Nullable)getBytes;
/**
 * GetHex retrieves the hex string representation of the bloom filter.
 */
- (NSString* _Nonnull)getHex;
/**
 * String returns a printable representation of the bloom filter.
 */
- (NSString* _Nonnull)string;
@end

/**
 * Bools represents a slice of bool.
 */
@interface GprobeBools : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the bool at the given index from the slice.
 */
- (BOOL)get:(long)index b:(BOOL* _Nullable)b error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the bool at the given index in the slice.
 */
- (BOOL)set:(long)index b:(BOOL)b error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of bool in the slice.
 */
- (long)size;
/**
 * String implements the Stringer interface.
 */
- (NSString* _Nonnull)string;
@end

/**
 * BoundContract is the base wrapper object that reflects a contract on the
ProbeChain network. It contains a collection of methods that are used by the
higher level contract bindings to operate.
 */
@interface GprobeBoundContract : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Call invokes the (constant) contract method with params as input values and
sets the output to result.
 */
- (BOOL)call:(GprobeCallOpts* _Nullable)opts out_:(GprobeInterfaces* _Nullable)out_ method:(NSString* _Nullable)method args:(GprobeInterfaces* _Nullable)args error:(NSError* _Nullable* _Nullable)error;
- (GprobeAddress* _Nullable)getAddress;
- (GprobeTransaction* _Nullable)getDeployer;
/**
 * RawTransact invokes the (paid) contract method with raw calldata as input values.
 */
- (GprobeTransaction* _Nullable)rawTransact:(GprobeTransactOpts* _Nullable)opts calldata:(NSData* _Nullable)calldata error:(NSError* _Nullable* _Nullable)error;
/**
 * Transact invokes the (paid) contract method with params as input values.
 */
- (GprobeTransaction* _Nullable)transact:(GprobeTransactOpts* _Nullable)opts method:(NSString* _Nullable)method args:(GprobeInterfaces* _Nullable)args error:(NSError* _Nullable* _Nullable)error;
/**
 * Transfer initiates a plain transaction to move funds to the contract, calling
its default method if one is available.
 */
- (GprobeTransaction* _Nullable)transfer:(GprobeTransactOpts* _Nullable)opts error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * CallMsg contains parameters for contract calls.
 */
@interface GprobeCallMsg : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewCallMsg creates an empty contract call parameter list.
 */
- (nullable instancetype)init;
- (NSData* _Nullable)getData;
- (GprobeAddress* _Nullable)getFrom;
- (int64_t)getGas;
- (GprobeBigInt* _Nullable)getGasPrice;
- (GprobeAddress* _Nullable)getTo;
- (GprobeBigInt* _Nullable)getValue;
- (void)setData:(NSData* _Nullable)data;
- (void)setFrom:(GprobeAddress* _Nullable)address;
- (void)setGas:(int64_t)gas;
- (void)setGasPrice:(GprobeBigInt* _Nullable)price;
- (void)setTo:(GprobeAddress* _Nullable)address;
- (void)setValue:(GprobeBigInt* _Nullable)value;
@end

/**
 * CallOpts is the collection of options to fine tune a contract call request.
 */
@interface GprobeCallOpts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewCallOpts creates a new option set for contract calls.
 */
- (nullable instancetype)init;
- (int64_t)getGasLimit;
- (BOOL)isPending;
- (void)setContext:(GprobeContext* _Nullable)context;
- (void)setFrom:(GprobeAddress* _Nullable)addr;
- (void)setGasLimit:(int64_t)limit;
- (void)setPending:(BOOL)pending;
@end

/**
 * Context carries a deadline, a cancellation signal, and other values across API
boundaries.
 */
@interface GprobeContext : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewContext returns a non-nil, empty Context. It is never canceled, has no
values, and has no deadline. It is typically used by the main function,
initialization, and tests, and as the top-level Context for incoming requests.
 */
- (nullable instancetype)init;
/**
 * WithCancel returns a copy of the original context with cancellation mechanism
included.

Canceling this context releases resources associated with it, so code should
call cancel as soon as the operations running in this Context complete.
 */
- (GprobeContext* _Nullable)withCancel;
/**
 * WithDeadline returns a copy of the original context with the deadline adjusted
to be no later than the specified time.

Canceling this context releases resources associated with it, so code should
call cancel as soon as the operations running in this Context complete.
 */
- (GprobeContext* _Nullable)withDeadline:(int64_t)sec nsec:(int64_t)nsec;
/**
 * WithTimeout returns a copy of the original context with the deadline adjusted
to be no later than now + the duration specified.

Canceling this context releases resources associated with it, so code should
call cancel as soon as the operations running in this Context complete.
 */
- (GprobeContext* _Nullable)withTimeout:(int64_t)nsec;
@end

/**
 * DilithiumKeyInfo contains metadata about a stored Dilithium key.
 */
@interface GprobeDilithiumKeyInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull publicKey;
@property (nonatomic) NSString* _Nonnull keyFile;
@end

/**
 * DilithiumKeyStore manages Dilithium post-quantum keys for SmartLight nodes.
Keys are encrypted at rest with AES-256-GCM. On iOS, the AES key should
be derived from a Secure Enclave ECDH operation (handled by Swift layer).
 */
@interface GprobeDilithiumKeyStore : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewDilithiumKeyStore creates a new Dilithium key store.
 */
- (nullable instancetype)init:(NSString* _Nullable)keyDir;
/**
 * GenerateKey generates a new Dilithium key pair, encrypts the private key,
and stores it on disk. Returns the key info.
The passphrase is used to derive the AES-256 encryption key.
On iOS, the Swift layer should use Secure Enclave-derived key instead.
 */
- (GprobeDilithiumKeyInfo* _Nullable)generateKey:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * GetAddress returns the ProbeChain address derived from a Dilithium public key.
 */
- (NSString* _Nonnull)getAddress:(NSString* _Nullable)pubKeyHex error:(NSError* _Nullable* _Nullable)error;
/**
 * GetPublicKey returns the public key bytes for a stored key.
 */
- (NSData* _Nullable)getPublicKey:(NSString* _Nullable)address error:(NSError* _Nullable* _Nullable)error;
/**
 * ListKeys returns all stored Dilithium key infos.
 */
- (NSString* _Nonnull)listKeys:(NSError* _Nullable* _Nullable)error;
/**
 * LoadKey loads and decrypts a Dilithium private key from the keystore.
 */
- (NSData* _Nullable)loadKey:(NSString* _Nullable)address passphrase:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * Sign signs a message using the Dilithium private key.
 */
- (NSData* _Nullable)sign:(NSData* _Nullable)privKeyBytes message:(NSData* _Nullable)message error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Enode represents a host on the network.
 */
@interface GprobeEnode : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewEnode parses a node designator.

There are two basic forms of node designators
  - incomplete nodes, which only have the public key (node ID)
  - complete nodes, which contain the public key and IP/Port information

For incomplete nodes, the designator must look like one of these

   enode://<hex node id>
   <hex node id>

For complete nodes, the node ID is encoded in the username portion
of the URL, separated from the host by an @ sign. The hostname can
only be given as an IP address, DNS domain names are not allowed.
The port in the host name section is the TCP listening port. If the
TCP and UDP (discovery) ports differ, the UDP port is specified as
query parameter "discport".

In the following example, the node URL describes
a node with IP address 10.3.58.6, TCP listening port 30303
and UDP discovery port 30301.

   enode://<hex node id>@10.3.58.6:30303?discport=30301
 */
- (nullable instancetype)init:(NSString* _Nullable)rawurl;
@end

/**
 * Enodes represents a slice of accounts.
 */
@interface GprobeEnodes : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewEnodes creates a slice of uninitialized enodes.
 */
- (nullable instancetype)init:(long)size;
/**
 * NewEnodesEmpty creates an empty slice of Enode values.
 */
- (nullable instancetype)initEmpty;
/**
 * Append adds a new enode element to the end of the slice.
 */
- (void)append:(GprobeEnode* _Nullable)enode;
/**
 * Get returns the enode at the given index from the slice.
 */
- (GprobeEnode* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the enode at the given index in the slice.
 */
- (BOOL)set:(long)index enode:(GprobeEnode* _Nullable)enode error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of enodes in the slice.
 */
- (long)size;
@end

/**
 * FilterQuery contains options for contract log filtering.
 */
@interface GprobeFilterQuery : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewFilterQuery creates an empty filter query for contract log filtering.
 */
- (nullable instancetype)init;
- (GprobeAddresses* _Nullable)getAddresses;
- (GprobeBigInt* _Nullable)getFromBlock;
- (GprobeBigInt* _Nullable)getToBlock;
- (GprobeTopics* _Nullable)getTopics;
- (void)setAddresses:(GprobeAddresses* _Nullable)addresses;
- (void)setFromBlock:(GprobeBigInt* _Nullable)fromBlock;
- (void)setToBlock:(GprobeBigInt* _Nullable)toBlock;
- (void)setTopics:(GprobeTopics* _Nullable)topics;
@end

/**
 * Hash represents the 32 byte Keccak256 hash of arbitrary data.
 */
@interface GprobeHash : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewHashFromBytes converts a slice of bytes to a hash value.
 */
- (nullable instancetype)initFromBytes:(NSData* _Nullable)binary;
/**
 * NewHashFromHex converts a hex string to a hash value.
 */
- (nullable instancetype)initFromHex:(NSString* _Nullable)hex;
/**
 * GetBytes retrieves the byte representation of the hash.
 */
- (NSData* _Nullable)getBytes;
/**
 * GetHex retrieves the hex string representation of the hash.
 */
- (NSString* _Nonnull)getHex;
/**
 * SetBytes sets the specified slice of bytes as the hash value.
 */
- (BOOL)setBytes:(NSData* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * SetHex sets the specified hex string as the hash value.
 */
- (BOOL)setHex:(NSString* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * String implements Stringer interface for printable representation of the hash.
 */
- (NSString* _Nonnull)string;
@end

/**
 * Hashes represents a slice of hashes.
 */
@interface GprobeHashes : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewHashes creates a slice of uninitialized Hashes.
 */
- (nullable instancetype)init:(long)size;
/**
 * NewHashesEmpty creates an empty slice of Hashes values.
 */
- (nullable instancetype)initEmpty;
/**
 * Append adds a new Hash element to the end of the slice.
 */
- (void)append:(GprobeHash* _Nullable)hash;
/**
 * Get returns the hash at the given index from the slice.
 */
- (GprobeHash* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the Hash at the given index in the slice.
 */
- (BOOL)set:(long)index hash:(GprobeHash* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of hashes in the slice.
 */
- (long)size;
@end

/**
 * Header represents a block header in the ProbeChain blockchain.
 */
@interface GprobeHeader : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewHeaderFromJSON parses a header from a JSON data dump.
 */
- (nullable instancetype)initFromJSON:(NSString* _Nullable)data;
/**
 * NewHeaderFromRLP parses a header from an RLP data dump.
 */
- (nullable instancetype)initFromRLP:(NSData* _Nullable)data;
/**
 * EncodeJSON encodes a header into a JSON data dump.
 */
- (NSString* _Nonnull)encodeJSON:(NSError* _Nullable* _Nullable)error;
/**
 * EncodeRLP encodes a header into an RLP data dump.
 */
- (NSData* _Nullable)encodeRLP:(NSError* _Nullable* _Nullable)error;
- (GprobeBloom* _Nullable)getBloom;
- (GprobeAddress* _Nullable)getCoinbase;
- (GprobeBigInt* _Nullable)getDifficulty;
- (NSData* _Nullable)getExtra;
- (int64_t)getGasLimit;
- (int64_t)getGasUsed;
- (GprobeHash* _Nullable)getHash;
- (GprobeHash* _Nullable)getMixDigest;
- (GprobeNonce* _Nullable)getNonce;
- (int64_t)getNumber;
- (GprobeHash* _Nullable)getParentHash;
- (GprobeHash* _Nullable)getReceiptHash;
- (GprobeHash* _Nullable)getRoot;
- (int64_t)getTime;
- (GprobeHash* _Nullable)getTxHash;
- (GprobeHash* _Nullable)getUncleHash;
/**
 * String returns a printable representation of the header.
 */
- (NSString* _Nonnull)string;
@end

/**
 * Headers represents a slice of headers.
 */
@interface GprobeHeaders : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the header at the given index from the slice.
 */
- (GprobeHeader* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of headers in the slice.
 */
- (long)size;
@end

/**
 * Interface represents a wrapped version of Go's interface{}, with the capacity
to store arbitrary data types.

Since it's impossible to get the arbitrary-ness converted between Go and mobile
platforms, we're using explicit getters and setters for the conversions. There
is of course no point in enumerating everything, just enough to support the
contract bindins requiring client side generated code.
 */
@interface GprobeInterface : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewInterface creates a new empty interface that can be used to pass around
generic types.
 */
- (nullable instancetype)init;
- (GprobeAddress* _Nullable)getAddress;
- (GprobeAddresses* _Nullable)getAddresses;
- (GprobeBigInt* _Nullable)getBigInt;
- (GprobeBigInts* _Nullable)getBigInts;
- (GprobeBinaries* _Nullable)getBinaries;
- (NSData* _Nullable)getBinary;
- (BOOL)getBool;
- (GprobeBools* _Nullable)getBools;
- (GprobeHash* _Nullable)getHash;
- (GprobeHashes* _Nullable)getHashes;
- (int16_t)getInt16;
- (GprobeBigInts* _Nullable)getInt16s;
- (int32_t)getInt32;
- (GprobeBigInts* _Nullable)getInt32s;
- (int64_t)getInt64;
- (GprobeBigInts* _Nullable)getInt64s;
- (int8_t)getInt8;
- (GprobeBigInts* _Nullable)getInt8s;
- (NSString* _Nonnull)getString;
- (GprobeStrings* _Nullable)getStrings;
- (GprobeBigInt* _Nullable)getUint16;
- (GprobeBigInts* _Nullable)getUint16s;
- (GprobeBigInt* _Nullable)getUint32;
- (GprobeBigInts* _Nullable)getUint32s;
- (GprobeBigInt* _Nullable)getUint64;
- (GprobeBigInts* _Nullable)getUint64s;
- (GprobeBigInt* _Nullable)getUint8;
- (GprobeBigInts* _Nullable)getUint8s;
- (void)setAddress:(GprobeAddress* _Nullable)address;
- (void)setAddresses:(GprobeAddresses* _Nullable)addrs;
- (void)setBigInt:(GprobeBigInt* _Nullable)bigint;
- (void)setBigInts:(GprobeBigInts* _Nullable)bigints;
- (void)setBinaries:(GprobeBinaries* _Nullable)binaries;
- (void)setBinary:(NSData* _Nullable)binary;
- (void)setBool:(BOOL)b;
- (void)setBools:(GprobeBools* _Nullable)bs;
- (void)setDefaultAddress;
- (void)setDefaultAddresses;
- (void)setDefaultBigInt;
- (void)setDefaultBigInts;
- (void)setDefaultBinaries;
- (void)setDefaultBinary;
- (void)setDefaultBool;
- (void)setDefaultBools;
- (void)setDefaultHash;
- (void)setDefaultHashes;
- (void)setDefaultInt16;
- (void)setDefaultInt16s;
- (void)setDefaultInt32;
- (void)setDefaultInt32s;
- (void)setDefaultInt64;
- (void)setDefaultInt64s;
- (void)setDefaultInt8;
- (void)setDefaultInt8s;
- (void)setDefaultString;
- (void)setDefaultStrings;
- (void)setDefaultUint16;
- (void)setDefaultUint16s;
- (void)setDefaultUint32;
- (void)setDefaultUint32s;
- (void)setDefaultUint64;
- (void)setDefaultUint64s;
- (void)setDefaultUint8;
- (void)setDefaultUint8s;
- (void)setHash:(GprobeHash* _Nullable)hash;
- (void)setHashes:(GprobeHashes* _Nullable)hashes;
- (void)setInt16:(int16_t)n;
- (void)setInt16s:(GprobeBigInts* _Nullable)bigints;
- (void)setInt32:(int32_t)n;
- (void)setInt32s:(GprobeBigInts* _Nullable)bigints;
- (void)setInt64:(int64_t)n;
- (void)setInt64s:(GprobeBigInts* _Nullable)bigints;
- (void)setInt8:(int8_t)n;
- (void)setInt8s:(GprobeBigInts* _Nullable)bigints;
- (void)setString:(NSString* _Nullable)str;
- (void)setStrings:(GprobeStrings* _Nullable)strs;
- (void)setUint16:(GprobeBigInt* _Nullable)bigint;
- (void)setUint16s:(GprobeBigInts* _Nullable)bigints;
- (void)setUint32:(GprobeBigInt* _Nullable)bigint;
- (void)setUint32s:(GprobeBigInts* _Nullable)bigints;
- (void)setUint64:(GprobeBigInt* _Nullable)bigint;
- (void)setUint64s:(GprobeBigInts* _Nullable)bigints;
- (void)setUint8:(GprobeBigInt* _Nullable)bigint;
- (void)setUint8s:(GprobeBigInts* _Nullable)bigints;
@end

/**
 * Interfaces is a slices of wrapped generic objects.
 */
@interface GprobeInterfaces : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewInterfaces creates a slice of uninitialized interfaces.
 */
- (nullable instancetype)init:(long)size;
/**
 * Get returns the bigint at the given index from the slice.
Notably the returned value can be changed without affecting the
interfaces itself.
 */
- (GprobeInterface* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the big int at the given index in the slice.
 */
- (BOOL)set:(long)index object:(GprobeInterface* _Nullable)object error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of interfaces in the slice.
 */
- (long)size;
@end

/**
 * KeyStore manages a key storage directory on disk.
 */
@interface GprobeKeyStore : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewKeyStore creates a keystore for the given directory.
 */
- (nullable instancetype)init:(NSString* _Nullable)keydir scryptN:(long)scryptN scryptP:(long)scryptP;
/**
 * DeleteAccount deletes the key matched by account if the passphrase is correct.
If a contains no filename, the address must match a unique key.
 */
- (BOOL)deleteAccount:(GprobeAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * ExportKey exports as a JSON key, encrypted with newPassphrase.
 */
- (NSData* _Nullable)exportKey:(GprobeAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase newPassphrase:(NSString* _Nullable)newPassphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * GetAccounts returns all key files present in the directory.
 */
- (GprobeAccounts* _Nullable)getAccounts;
/**
 * HasAddress reports whprobeer a key with the given address is present.
 */
- (BOOL)hasAddress:(GprobeAddress* _Nullable)address;
/**
 * ImportECDSAKey stores the given encrypted JSON key into the key directory.
 */
- (GprobeAccount* _Nullable)importECDSAKey:(NSData* _Nullable)key passphrase:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * ImportKey stores the given encrypted JSON key into the key directory.
 */
- (GprobeAccount* _Nullable)importKey:(NSData* _Nullable)keyJSON passphrase:(NSString* _Nullable)passphrase newPassphrase:(NSString* _Nullable)newPassphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * ImportPreSaleKey decrypts the given Probeum presale wallet and stores
a key file in the key directory. The key file is encrypted with the same passphrase.
 */
- (GprobeAccount* _Nullable)importPreSaleKey:(NSData* _Nullable)keyJSON passphrase:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * Lock removes the private key with the given address from memory.
 */
- (BOOL)lock:(GprobeAddress* _Nullable)address error:(NSError* _Nullable* _Nullable)error;
/**
 * NewAccount generates a new key and stores it into the key directory,
encrypting it with the passphrase.
 */
- (GprobeAccount* _Nullable)newAccount:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * SignHash calculates a ECDSA signature for the given hash. The produced signature
is in the [R || S || V] format where V is 0 or 1.
 */
- (NSData* _Nullable)signHash:(GprobeAddress* _Nullable)address hash:(NSData* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * SignHashPassphrase signs hash if the private key matching the given address can
be decrypted with the given passphrase. The produced signature is in the
[R || S || V] format where V is 0 or 1.
 */
- (NSData* _Nullable)signHashPassphrase:(GprobeAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase hash:(NSData* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * SignTx signs the given transaction with the requested account.
 */
- (GprobeTransaction* _Nullable)signTx:(GprobeAccount* _Nullable)account tx:(GprobeTransaction* _Nullable)tx chainID:(GprobeBigInt* _Nullable)chainID error:(NSError* _Nullable* _Nullable)error;
/**
 * SignTxPassphrase signs the transaction if the private key matching the
given address can be decrypted with the given passphrase.
 */
- (GprobeTransaction* _Nullable)signTxPassphrase:(GprobeAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase tx:(GprobeTransaction* _Nullable)tx chainID:(GprobeBigInt* _Nullable)chainID error:(NSError* _Nullable* _Nullable)error;
/**
 * TimedUnlock unlocks the given account with the passphrase. The account stays
unlocked for the duration of timeout (nanoseconds). A timeout of 0 unlocks the
account until the program exits. The account must match a unique key file.

If the account address is already unlocked for a duration, TimedUnlock extends or
shortens the active unlock timeout. If the address was previously unlocked
indefinitely the timeout is not altered.
 */
- (BOOL)timedUnlock:(GprobeAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase timeout:(int64_t)timeout error:(NSError* _Nullable* _Nullable)error;
/**
 * Unlock unlocks the given account indefinitely.
 */
- (BOOL)unlock:(GprobeAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
/**
 * UpdateAccount changes the passphrase of an existing account.
 */
- (BOOL)updateAccount:(GprobeAccount* _Nullable)account passphrase:(NSString* _Nullable)passphrase newPassphrase:(NSString* _Nullable)newPassphrase error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Log represents a contract log event. These events are generated by the LOG
opcode and stored/indexed by the node.
 */
@interface GprobeLog : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (GprobeAddress* _Nullable)getAddress;
- (GprobeHash* _Nullable)getBlockHash;
- (int64_t)getBlockNumber;
- (NSData* _Nullable)getData;
- (long)getIndex;
- (GprobeHashes* _Nullable)getTopics;
- (GprobeHash* _Nullable)getTxHash;
- (long)getTxIndex;
@end

/**
 * Logs represents a slice of VM logs.
 */
@interface GprobeLogs : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the log at the given index from the slice.
 */
- (GprobeLog* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of logs in the slice.
 */
- (long)size;
@end

@interface GprobeMobileSigner : NSObject <goSeqRefInterface, GprobeSigner> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (GprobeTransaction* _Nullable)sign:(GprobeAddress* _Nullable)addr unsignedTx:(GprobeTransaction* _Nullable)unsignedTx error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Node represents a Gprobe Probeum node instance.
 */
@interface GprobeNode : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewNode creates and configures a new Gprobe node.
 */
- (nullable instancetype)init:(NSString* _Nullable)datadir config:(GprobeNodeConfig* _Nullable)config;
/**
 * Close terminates a running node along with all it's services, tearing internal state
down. It is not possible to restart a closed node.
 */
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
/**
 * GetNodeInfo gathers and returns a collection of metadata known about the host.
 */
- (GprobeNodeInfo* _Nullable)getNodeInfo;
/**
 * GetPeersInfo returns an array of metadata objects describing connected peers.
 */
- (GprobePeerInfos* _Nullable)getPeersInfo;
/**
 * GetProbeumClient retrieves a client to access the ProbeChain subsystem.
 */
- (GprobeProbeumClient* _Nullable)getProbeumClient:(NSError* _Nullable* _Nullable)error;
/**
 * Start creates a live P2P node and starts running it.
 */
- (BOOL)start:(NSError* _Nullable* _Nullable)error;
/**
 * Stop terminates a running node along with all its services. If the node was not started,
an error is returned. It is not possible to restart a stopped node.

Deprecated: use Close()
 */
- (BOOL)stop:(NSError* _Nullable* _Nullable)error;
@end

/**
 * NodeConfig represents the collection of configuration values to fine tune the Gprobe
node embedded into a mobile process. The available values are a subset of the
entire API provided by go-probeum to reduce the maintenance surface and dev
complexity.
 */
@interface GprobeNodeConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewNodeConfig creates a new node option set, initialized to the default values.
 */
- (nullable instancetype)init;
/**
 * Bootstrap nodes used to establish connectivity with the rest of the network.
 */
@property (nonatomic) GprobeEnodes* _Nullable bootstrapNodes;
/**
 * MaxPeers is the maximum number of peers that can be connected. If this is
set to zero, then only the configured static and trusted peers can connect.
 */
@property (nonatomic) long maxPeers;
/**
 * ProbeumEnabled specifies whprobeer the node should run the ProbeChain protocol.
 */
@property (nonatomic) BOOL probeumEnabled;
/**
 * ProbeumNetworkID is the network identifier used by the ProbeChain protocol to
decide if remote peers should be accepted or not.
 */
@property (nonatomic) int64_t probeumNetworkID;
/**
 * ProbeumGenesis is the genesis JSON to use to seed the blockchain with. An
empty genesis state is equivalent to using the mainnet's state.
 */
@property (nonatomic) NSString* _Nonnull probeumGenesis;
/**
 * ProbeumDatabaseCache is the system memory in MB to allocate for database caching.
A minimum of 16MB is always reserved.
 */
@property (nonatomic) long probeumDatabaseCache;
/**
 * ProbeumNetStats is a netstats connection string to use to report various
chain, transaction and node stats to a monitoring server.

It has the form "nodename:secret@host:port"
 */
@property (nonatomic) NSString* _Nonnull probeumNetStats;
/**
 * Listening address of pprof server.
 */
@property (nonatomic) NSString* _Nonnull pprofAddress;
/**
 * AddBootstrapNode adds an additional bootstrap node to the node config.
 */
- (void)addBootstrapNode:(GprobeEnode* _Nullable)node;
/**
 * EncodeJSON encodes a NodeConfig into a JSON data dump.
 */
- (NSString* _Nonnull)encodeJSON:(NSError* _Nullable* _Nullable)error;
/**
 * String returns a printable representation of the node config.
 */
- (NSString* _Nonnull)string;
@end

/**
 * NodeInfo represents pi short summary of the information known about the host.
 */
@interface GprobeNodeInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (long)getDiscoveryPort;
- (NSString* _Nonnull)getEnode;
- (NSString* _Nonnull)getID;
- (NSString* _Nonnull)getIP;
- (NSString* _Nonnull)getListenerAddress;
- (long)getListenerPort;
- (NSString* _Nonnull)getName;
- (GprobeStrings* _Nullable)getProtocols;
@end

/**
 * A Nonce is a 64-bit hash which proves (combined with the mix-hash) that
a sufficient amount of computation has been carried out on a block.
 */
@interface GprobeNonce : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * GetBytes retrieves the byte representation of the block nonce.
 */
- (NSData* _Nullable)getBytes;
/**
 * GetHex retrieves the hex string representation of the block nonce.
 */
- (NSString* _Nonnull)getHex;
/**
 * String returns a printable representation of the nonce.
 */
- (NSString* _Nonnull)string;
@end

/**
 * PeerInfo represents pi short summary of the information known about pi connected peer.
 */
@interface GprobePeerInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (GprobeStrings* _Nullable)getCaps;
- (NSString* _Nonnull)getID;
- (NSString* _Nonnull)getLocalAddress;
- (NSString* _Nonnull)getName;
- (NSString* _Nonnull)getRemoteAddress;
@end

/**
 * PeerInfos represents a slice of infos about remote peers.
 */
@interface GprobePeerInfos : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the peer info at the given index from the slice.
 */
- (GprobePeerInfo* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of peer info entries in the slice.
 */
- (long)size;
@end

/**
 * ProbeumClient provides access to the ProbeChain APIs.
 */
@interface GprobeProbeumClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewProbeumClient connects a client to the given URL.
 */
- (nullable instancetype)init:(NSString* _Nullable)rawurl;
/**
 * CallContract executes a message call transaction, which is directly executed in the VM
of the node, but never mined into the blockchain.

blockNumber selects the block height at which the call runs. It can be <0, in which
case the code is taken from the latest known block. Note that state from very old
blocks might not be available.
 */
- (NSData* _Nullable)callContract:(GprobeContext* _Nullable)ctx msg:(GprobeCallMsg* _Nullable)msg number:(int64_t)number error:(NSError* _Nullable* _Nullable)error;
/**
 * EstimateGas tries to estimate the gas needed to execute a specific transaction based on
the current pending state of the backend blockchain. There is no guarantee that this is
the true gas limit requirement as other transactions may be added or removed by miners,
but it should provide a basis for setting a reasonable default.
 */
- (BOOL)estimateGas:(GprobeContext* _Nullable)ctx msg:(GprobeCallMsg* _Nullable)msg gas:(int64_t* _Nullable)gas error:(NSError* _Nullable* _Nullable)error;
/**
 * FilterLogs executes a filter query.
 */
- (GprobeLogs* _Nullable)filterLogs:(GprobeContext* _Nullable)ctx query:(GprobeFilterQuery* _Nullable)query error:(NSError* _Nullable* _Nullable)error;
/**
 * GetBalanceAt returns the wei balance of the given account.
The block number can be <0, in which case the balance is taken from the latest known block.
 */
- (GprobeBigInt* _Nullable)getBalanceAt:(GprobeContext* _Nullable)ctx account:(GprobeAddress* _Nullable)account number:(int64_t)number error:(NSError* _Nullable* _Nullable)error;
/**
 * GetBlockByHash returns the given full block.
 */
- (GprobeBlock* _Nullable)getBlockByHash:(GprobeContext* _Nullable)ctx hash:(GprobeHash* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * GetBlockByNumber returns a block from the current canonical chain. If number is <0, the
latest known block is returned.
 */
- (GprobeBlock* _Nullable)getBlockByNumber:(GprobeContext* _Nullable)ctx number:(int64_t)number error:(NSError* _Nullable* _Nullable)error;
/**
 * GetCodeAt returns the contract code of the given account.
The block number can be <0, in which case the code is taken from the latest known block.
 */
- (NSData* _Nullable)getCodeAt:(GprobeContext* _Nullable)ctx account:(GprobeAddress* _Nullable)account number:(int64_t)number error:(NSError* _Nullable* _Nullable)error;
/**
 * GetHeaderByHash returns the block header with the given hash.
 */
- (GprobeHeader* _Nullable)getHeaderByHash:(GprobeContext* _Nullable)ctx hash:(GprobeHash* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * GetHeaderByNumber returns a block header from the current canonical chain. If number is <0,
the latest known header is returned.
 */
- (GprobeHeader* _Nullable)getHeaderByNumber:(GprobeContext* _Nullable)ctx number:(int64_t)number error:(NSError* _Nullable* _Nullable)error;
/**
 * GetNonceAt returns the account nonce of the given account.
The block number can be <0, in which case the nonce is taken from the latest known block.
 */
- (BOOL)getNonceAt:(GprobeContext* _Nullable)ctx account:(GprobeAddress* _Nullable)account number:(int64_t)number nonce:(int64_t* _Nullable)nonce error:(NSError* _Nullable* _Nullable)error;
/**
 * GetPendingBalanceAt returns the wei balance of the given account in the pending state.
 */
- (GprobeBigInt* _Nullable)getPendingBalanceAt:(GprobeContext* _Nullable)ctx account:(GprobeAddress* _Nullable)account error:(NSError* _Nullable* _Nullable)error;
/**
 * GetPendingCodeAt returns the contract code of the given account in the pending state.
 */
- (NSData* _Nullable)getPendingCodeAt:(GprobeContext* _Nullable)ctx account:(GprobeAddress* _Nullable)account error:(NSError* _Nullable* _Nullable)error;
/**
 * GetPendingNonceAt returns the account nonce of the given account in the pending state.
This is the nonce that should be used for the next transaction.
 */
- (BOOL)getPendingNonceAt:(GprobeContext* _Nullable)ctx account:(GprobeAddress* _Nullable)account nonce:(int64_t* _Nullable)nonce error:(NSError* _Nullable* _Nullable)error;
/**
 * GetPendingStorageAt returns the value of key in the contract storage of the given account in the pending state.
 */
- (NSData* _Nullable)getPendingStorageAt:(GprobeContext* _Nullable)ctx account:(GprobeAddress* _Nullable)account key:(GprobeHash* _Nullable)key error:(NSError* _Nullable* _Nullable)error;
/**
 * GetPendingTransactionCount returns the total number of transactions in the pending state.
 */
- (BOOL)getPendingTransactionCount:(GprobeContext* _Nullable)ctx count:(long* _Nullable)count error:(NSError* _Nullable* _Nullable)error;
/**
 * GetStorageAt returns the value of key in the contract storage of the given account.
The block number can be <0, in which case the value is taken from the latest known block.
 */
- (NSData* _Nullable)getStorageAt:(GprobeContext* _Nullable)ctx account:(GprobeAddress* _Nullable)account key:(GprobeHash* _Nullable)key number:(int64_t)number error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTransactionByHash returns the transaction with the given hash.
 */
- (GprobeTransaction* _Nullable)getTransactionByHash:(GprobeContext* _Nullable)ctx hash:(GprobeHash* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTransactionCount returns the total number of transactions in the given block.
 */
- (BOOL)getTransactionCount:(GprobeContext* _Nullable)ctx hash:(GprobeHash* _Nullable)hash count:(long* _Nullable)count error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTransactionInBlock returns a single transaction at index in the given block.
 */
- (GprobeTransaction* _Nullable)getTransactionInBlock:(GprobeContext* _Nullable)ctx hash:(GprobeHash* _Nullable)hash index:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTransactionReceipt returns the receipt of a transaction by transaction hash.
Note that the receipt is not available for pending transactions.
 */
- (GprobeReceipt* _Nullable)getTransactionReceipt:(GprobeContext* _Nullable)ctx hash:(GprobeHash* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTransactionSender returns the sender address of a transaction. The transaction must
be included in blockchain at the given block and index.
 */
- (GprobeAddress* _Nullable)getTransactionSender:(GprobeContext* _Nullable)ctx tx:(GprobeTransaction* _Nullable)tx blockhash:(GprobeHash* _Nullable)blockhash index:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * PendingCallContract executes a message call transaction using the EVM.
The state seen by the contract call is the pending state.
 */
- (NSData* _Nullable)pendingCallContract:(GprobeContext* _Nullable)ctx msg:(GprobeCallMsg* _Nullable)msg error:(NSError* _Nullable* _Nullable)error;
/**
 * SendTransaction injects a signed transaction into the pending pool for execution.

If the transaction was a contract creation use the TransactionReceipt method to get the
contract address after the transaction has been mined.
 */
- (BOOL)sendTransaction:(GprobeContext* _Nullable)ctx tx:(GprobeTransaction* _Nullable)tx error:(NSError* _Nullable* _Nullable)error;
/**
 * SubscribeFilterLogs subscribes to the results of a streaming filter query.
 */
- (GprobeSubscription* _Nullable)subscribeFilterLogs:(GprobeContext* _Nullable)ctx query:(GprobeFilterQuery* _Nullable)query handler:(id<GprobeFilterLogsHandler> _Nullable)handler buffer:(long)buffer error:(NSError* _Nullable* _Nullable)error;
/**
 * SubscribeNewHead subscribes to notifications about the current blockchain head
on the given channel.
 */
- (GprobeSubscription* _Nullable)subscribeNewHead:(GprobeContext* _Nullable)ctx handler:(id<GprobeNewHeadHandler> _Nullable)handler buffer:(long)buffer error:(NSError* _Nullable* _Nullable)error;
/**
 * SuggestGasPrice retrieves the currently suggested gas price to allow a timely
execution of a transaction.
 */
- (GprobeBigInt* _Nullable)suggestGasPrice:(GprobeContext* _Nullable)ctx error:(NSError* _Nullable* _Nullable)error;
/**
 * SyncProgress retrieves the current progress of the sync algorithm. If there's
no sync currently running, it returns nil.
 */
- (GprobeSyncProgress* _Nullable)syncProgress:(GprobeContext* _Nullable)ctx error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Receipt represents the results of a transaction.
 */
@interface GprobeReceipt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewReceiptFromJSON parses a transaction receipt from a JSON data dump.
 */
- (nullable instancetype)initFromJSON:(NSString* _Nullable)data;
/**
 * NewReceiptFromRLP parses a transaction receipt from an RLP data dump.
 */
- (nullable instancetype)initFromRLP:(NSData* _Nullable)data;
/**
 * EncodeJSON encodes a transaction receipt into a JSON data dump.
 */
- (NSString* _Nonnull)encodeJSON:(NSError* _Nullable* _Nullable)error;
/**
 * EncodeRLP encodes a transaction receipt into an RLP data dump.
 */
- (NSData* _Nullable)encodeRLP:(NSError* _Nullable* _Nullable)error;
- (GprobeBloom* _Nullable)getBloom;
- (GprobeAddress* _Nullable)getContractAddress;
- (int64_t)getCumulativeGasUsed;
- (int64_t)getGasUsed;
- (GprobeLogs* _Nullable)getLogs;
- (NSData* _Nullable)getPostState;
- (long)getStatus;
- (GprobeHash* _Nullable)getTxHash;
/**
 * String returns a printable representation of the receipt.
 */
- (NSString* _Nonnull)string;
@end

/**
 * SmartLightNode represents a SmartLight node instance.
 */
@interface GprobeSmartLightNode : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewSmartLightNode creates and configures a SmartLight node.
It runs a LES light client underneath with SmartLight services on top.
 */
- (nullable instancetype)init:(NSString* _Nullable)datadir config:(GprobeSmartLightNodeConfig* _Nullable)config;
/**
 * Close terminates a running SmartLight node.
 */
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
/**
 * GetBehaviorScore returns the JSON-encoded local behavior score.
 */
- (NSString* _Nonnull)getBehaviorScore:(NSError* _Nullable* _Nullable)error;
/**
 * GetNodeInfo returns metadata about the SmartLight node.
 */
- (GprobeNodeInfo* _Nullable)getNodeInfo;
/**
 * GetPeersInfo returns connected peer information.
 */
- (GprobePeerInfos* _Nullable)getPeersInfo;
/**
 * GetPowerMode returns the current power mode.
 */
- (long)getPowerMode;
/**
 * GetProbeumClient retrieves a client to access the ProbeChain subsystem.
 */
- (GprobeProbeumClient* _Nullable)getProbeumClient:(NSError* _Nullable* _Nullable)error;
/**
 * GetRewardStats returns the JSON-encoded reward statistics.
 */
- (NSString* _Nonnull)getRewardStats:(NSError* _Nullable* _Nullable)error;
/**
 * GetSyncedBlockNumber returns the current highest synced block number.
 */
- (int64_t)getSyncedBlockNumber;
/**
 * IsRunning returns whether the SmartLight engine is running.
 */
- (BOOL)isRunning;
/**
 * SetPowerMode changes the SmartLight power mode.
0 = Full (charging), 1 = Eco (battery > 30%), 2 = Sleep (battery < 15%).
 */
- (void)setPowerMode:(long)mode;
/**
 * Start creates a live P2P node and starts SmartLight services.
 */
- (BOOL)start:(NSError* _Nullable* _Nullable)error;
/**
 * Stop terminates the node.
 */
- (BOOL)stop:(NSError* _Nullable* _Nullable)error;
@end

/**
 * SmartLightNodeConfig represents configuration for a SmartLight node.
SmartLight nodes are lightweight PoB participants that contribute through
ACK attestations, heartbeat proofs, GNSS time samples, and agent tasks.
 */
@interface GprobeSmartLightNodeConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewSmartLightNodeConfig creates a new SmartLight node config with defaults.
 */
- (nullable instancetype)init;
/**
 * Bootstrap nodes used to establish connectivity.
 */
@property (nonatomic) GprobeEnodes* _Nullable bootstrapNodes;
/**
 * MaxPeers is the maximum number of peers that can be connected.
 */
@property (nonatomic) long maxPeers;
/**
 * ProbeumNetworkID is the network identifier.
 */
@property (nonatomic) int64_t probeumNetworkID;
/**
 * ProbeumGenesis is the genesis JSON.
 */
@property (nonatomic) NSString* _Nonnull probeumGenesis;
/**
 * ProbeumDatabaseCache is the system memory in MB for database caching.
SmartLight uses 50-80 MB (vs 16 MB for LES).
 */
@property (nonatomic) long probeumDatabaseCache;
/**
 * ProbeumNetStats is the netstats connection string.
 */
@property (nonatomic) NSString* _Nonnull probeumNetStats;
/**
 * HeartbeatInterval is blocks between heartbeat proofs (default: 100).
 */
@property (nonatomic) long heartbeatInterval;
/**
 * GNSSEnabled enables GNSS time sampling from device GPS.
 */
@property (nonatomic) BOOL gnssEnabled;
/**
 * MaxAgentTasks is max concurrent agent tasks (default: 2).
 */
@property (nonatomic) long maxAgentTasks;
/**
 * PowerMode: 0=Full, 1=Eco, 2=Sleep.
 */
@property (nonatomic) long powerMode;
@end

/**
 * Strings represents s slice of strs.
 */
@interface GprobeStrings : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the string at the given index from the slice.
 */
- (NSString* _Nonnull)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the string at the given index in the slice.
 */
- (BOOL)set:(long)index str:(NSString* _Nullable)str error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of strs in the slice.
 */
- (long)size;
/**
 * String implements the Stringer interface.
 */
- (NSString* _Nonnull)string;
@end

/**
 * Subscription represents an event subscription where events are
delivered on a data channel.
 */
@interface GprobeSubscription : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Unsubscribe cancels the sending of events to the data channel
and closes the error channel.
 */
- (void)unsubscribe;
@end

/**
 * SyncProgress gives progress indications when the node is synchronising with
the ProbeChain network.
 */
@interface GprobeSyncProgress : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (int64_t)getCurrentBlock;
- (int64_t)getHighestBlock;
- (int64_t)getKnownStates;
- (int64_t)getPulledStates;
- (int64_t)getStartingBlock;
@end

/**
 * Topics is a set of topic lists to filter events with.
 */
@interface GprobeTopics : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewTopics creates a slice of uninitialized Topics.
 */
- (nullable instancetype)init:(long)size;
/**
 * NewTopicsEmpty creates an empty slice of Topics values.
 */
- (nullable instancetype)initEmpty;
/**
 * Append adds a new topic list to the end of the slice.
 */
- (void)append:(GprobeHashes* _Nullable)topics;
/**
 * Get returns the topic list at the given index from the slice.
 */
- (GprobeHashes* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the topic list at the given index in the slice.
 */
- (BOOL)set:(long)index topics:(GprobeHashes* _Nullable)topics error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of topic lists inside the set
 */
- (long)size;
@end

/**
 * TransactOpts is the collection of authorization data required to create a
valid Probeum transaction.
 */
@interface GprobeTransactOpts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewTransactOpts creates a new option set for contract transaction.
 */
- (nullable instancetype)init;
- (GprobeAddress* _Nullable)getFrom;
- (int64_t)getGasLimit;
- (GprobeBigInt* _Nullable)getGasPrice;
- (int64_t)getNonce;
- (GprobeBigInt* _Nullable)getValue;
- (void)setContext:(GprobeContext* _Nullable)context;
- (void)setFrom:(GprobeAddress* _Nullable)from;
- (void)setGasLimit:(int64_t)limit;
- (void)setGasPrice:(GprobeBigInt* _Nullable)price;
- (void)setNonce:(int64_t)nonce;
- (void)setSigner:(id<GprobeSigner> _Nullable)s;
- (void)setValue:(GprobeBigInt* _Nullable)value;
@end

/**
 * Transaction represents a single Probeum transaction.
 */
@interface GprobeTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewTransaction creates a new transaction with the given properties. Contracts
can be created by transacting with a nil recipient.
 */
- (nullable instancetype)init:(int64_t)nonce to:(GprobeAddress* _Nullable)to amount:(GprobeBigInt* _Nullable)amount gasLimit:(int64_t)gasLimit gasPrice:(GprobeBigInt* _Nullable)gasPrice data:(NSData* _Nullable)data;
/**
 * NewTransactionFromJSON parses a transaction from a JSON data dump.
 */
- (nullable instancetype)initFromJSON:(NSString* _Nullable)data;
/**
 * NewTransactionFromRLP parses a transaction from an RLP data dump.
 */
- (nullable instancetype)initFromRLP:(NSData* _Nullable)data;
/**
 * EncodeJSON encodes a transaction into a JSON data dump.
 */
- (NSString* _Nonnull)encodeJSON:(NSError* _Nullable* _Nullable)error;
/**
 * EncodeRLP encodes a transaction into an RLP data dump.
 */
- (NSData* _Nullable)encodeRLP:(NSError* _Nullable* _Nullable)error;
- (GprobeBigInt* _Nullable)getCost;
- (NSData* _Nullable)getData;
/**
 * Deprecated: use ProbeumClient.TransactionSender
 */
- (GprobeAddress* _Nullable)getFrom:(GprobeBigInt* _Nullable)chainID error:(NSError* _Nullable* _Nullable)error;
- (int64_t)getGas;
- (GprobeBigInt* _Nullable)getGasPrice;
- (GprobeHash* _Nullable)getHash;
- (int64_t)getNonce;
/**
 * Deprecated: GetSigHash cannot know which signer to use.
 */
- (GprobeHash* _Nullable)getSigHash;
- (GprobeAddress* _Nullable)getTo;
- (GprobeBigInt* _Nullable)getValue;
/**
 * String returns a printable representation of the transaction.
 */
- (NSString* _Nonnull)string;
- (GprobeTransaction* _Nullable)withSignature:(NSData* _Nullable)sig chainID:(GprobeBigInt* _Nullable)chainID error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Transactions represents a slice of transactions.
 */
@interface GprobeTransactions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the transaction at the given index from the slice.
 */
- (GprobeTransaction* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of transactions in the slice.
 */
- (long)size;
@end

/**
 * LightScryptN is the N parameter of Scrypt encryption algorithm, using 4MB
memory and taking approximately 100ms CPU time on a modern processor.
 */
FOUNDATION_EXPORT const long GprobeLightScryptN;
/**
 * LightScryptP is the P parameter of Scrypt encryption algorithm, using 4MB
memory and taking approximately 100ms CPU time on a modern processor.
 */
FOUNDATION_EXPORT const long GprobeLightScryptP;
/**
 * StandardScryptN is the N parameter of Scrypt encryption algorithm, using 256MB
memory and taking approximately 1s CPU time on a modern processor.
 */
FOUNDATION_EXPORT const long GprobeStandardScryptN;
/**
 * StandardScryptP is the P parameter of Scrypt encryption algorithm, using 256MB
memory and taking approximately 1s CPU time on a modern processor.
 */
FOUNDATION_EXPORT const long GprobeStandardScryptP;

/**
 * BindContract creates a low level contract interface through which calls and
transactions may be made through.
 */
FOUNDATION_EXPORT GprobeBoundContract* _Nullable GprobeBindContract(GprobeAddress* _Nullable address, NSString* _Nullable abiJSON, GprobeProbeumClient* _Nullable client, NSError* _Nullable* _Nullable error);

/**
 * DecodeFromHex decodes a hex string with 0x prefix.
 */
FOUNDATION_EXPORT NSData* _Nullable GprobeDecodeFromHex(NSString* _Nullable s, NSError* _Nullable* _Nullable error);

/**
 * DeployContract deploys a contract onto the ProbeChain blockchain and binds the
deployment address with a wrapper.
 */
FOUNDATION_EXPORT GprobeBoundContract* _Nullable GprobeDeployContract(GprobeTransactOpts* _Nullable opts, NSString* _Nullable abiJSON, NSData* _Nullable bytecode, GprobeProbeumClient* _Nullable client, GprobeInterfaces* _Nullable args, NSError* _Nullable* _Nullable error);

/**
 * DilithiumPrivateKeySize returns the size of a Dilithium private key in bytes.
 */
FOUNDATION_EXPORT long GprobeDilithiumPrivateKeySize(void);

/**
 * DilithiumPublicKeySize returns the size of a Dilithium public key in bytes.
 */
FOUNDATION_EXPORT long GprobeDilithiumPublicKeySize(void);

/**
 * DilithiumSignatureSize returns the size of a Dilithium signature in bytes.
 */
FOUNDATION_EXPORT long GprobeDilithiumSignatureSize(void);

/**
 * EncodeToHex encodes b as a hex string with 0x prefix.
 */
FOUNDATION_EXPORT NSString* _Nonnull GprobeEncodeToHex(NSData* _Nullable b);

/**
 * FoundationBootnodes returns the enode URLs of the P2P bootstrap nodes operated
by the foundation running the V5 discovery protocol.
 */
FOUNDATION_EXPORT GprobeEnodes* _Nullable GprobeFoundationBootnodes(void);

/**
 * MainnetGenesis returns the JSON spec to use for the main ProbeChain network. It
is actually empty since that defaults to the hard coded binary genesis block.
 */
FOUNDATION_EXPORT NSString* _Nonnull GprobeMainnetGenesis(void);

/**
 * NewAddressFromBytes converts a slice of bytes to a hash value.
 */
FOUNDATION_EXPORT GprobeAddress* _Nullable GprobeNewAddressFromBytes(NSData* _Nullable binary, NSError* _Nullable* _Nullable error);

/**
 * NewAddressFromHex converts a hex string to a address value.
 */
FOUNDATION_EXPORT GprobeAddress* _Nullable GprobeNewAddressFromHex(NSString* _Nullable hex, NSError* _Nullable* _Nullable error);

/**
 * NewAddresses creates a slice of uninitialized addresses.
 */
FOUNDATION_EXPORT GprobeAddresses* _Nullable GprobeNewAddresses(long size);

/**
 * NewAddressesEmpty creates an empty slice of Addresses values.
 */
FOUNDATION_EXPORT GprobeAddresses* _Nullable GprobeNewAddressesEmpty(void);

/**
 * NewBigInt allocates and returns a new BigInt set to x.
 */
FOUNDATION_EXPORT GprobeBigInt* _Nullable GprobeNewBigInt(int64_t x);

/**
 * NewBigIntFromString allocates and returns a new BigInt set to x
interpreted in the provided base.
 */
FOUNDATION_EXPORT GprobeBigInt* _Nullable GprobeNewBigIntFromString(NSString* _Nullable x, long base);

/**
 * NewBigInts creates a slice of uninitialized big numbers.
 */
FOUNDATION_EXPORT GprobeBigInts* _Nullable GprobeNewBigInts(long size);

/**
 * NewBlockFromJSON parses a block from a JSON data dump.
 */
FOUNDATION_EXPORT GprobeBlock* _Nullable GprobeNewBlockFromJSON(NSString* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewBlockFromRLP parses a block from an RLP data dump.
 */
FOUNDATION_EXPORT GprobeBlock* _Nullable GprobeNewBlockFromRLP(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewCallMsg creates an empty contract call parameter list.
 */
FOUNDATION_EXPORT GprobeCallMsg* _Nullable GprobeNewCallMsg(void);

/**
 * NewCallOpts creates a new option set for contract calls.
 */
FOUNDATION_EXPORT GprobeCallOpts* _Nullable GprobeNewCallOpts(void);

/**
 * NewContext returns a non-nil, empty Context. It is never canceled, has no
values, and has no deadline. It is typically used by the main function,
initialization, and tests, and as the top-level Context for incoming requests.
 */
FOUNDATION_EXPORT GprobeContext* _Nullable GprobeNewContext(void);

/**
 * NewContractCreation creates a new transaction for deploying a new contract with
the given properties.
 */
FOUNDATION_EXPORT GprobeTransaction* _Nullable GprobeNewContractCreation(int64_t nonce, GprobeBigInt* _Nullable amount, int64_t gasLimit, GprobeBigInt* _Nullable gasPrice, NSData* _Nullable data);

/**
 * NewDilithiumKeyStore creates a new Dilithium key store.
 */
FOUNDATION_EXPORT GprobeDilithiumKeyStore* _Nullable GprobeNewDilithiumKeyStore(NSString* _Nullable keyDir);

/**
 * NewEnode parses a node designator.

There are two basic forms of node designators
  - incomplete nodes, which only have the public key (node ID)
  - complete nodes, which contain the public key and IP/Port information

For incomplete nodes, the designator must look like one of these

   enode://<hex node id>
   <hex node id>

For complete nodes, the node ID is encoded in the username portion
of the URL, separated from the host by an @ sign. The hostname can
only be given as an IP address, DNS domain names are not allowed.
The port in the host name section is the TCP listening port. If the
TCP and UDP (discovery) ports differ, the UDP port is specified as
query parameter "discport".

In the following example, the node URL describes
a node with IP address 10.3.58.6, TCP listening port 30303
and UDP discovery port 30301.

   enode://<hex node id>@10.3.58.6:30303?discport=30301
 */
FOUNDATION_EXPORT GprobeEnode* _Nullable GprobeNewEnode(NSString* _Nullable rawurl, NSError* _Nullable* _Nullable error);

/**
 * NewEnodes creates a slice of uninitialized enodes.
 */
FOUNDATION_EXPORT GprobeEnodes* _Nullable GprobeNewEnodes(long size);

/**
 * NewEnodesEmpty creates an empty slice of Enode values.
 */
FOUNDATION_EXPORT GprobeEnodes* _Nullable GprobeNewEnodesEmpty(void);

/**
 * NewFilterQuery creates an empty filter query for contract log filtering.
 */
FOUNDATION_EXPORT GprobeFilterQuery* _Nullable GprobeNewFilterQuery(void);

/**
 * NewHashFromBytes converts a slice of bytes to a hash value.
 */
FOUNDATION_EXPORT GprobeHash* _Nullable GprobeNewHashFromBytes(NSData* _Nullable binary, NSError* _Nullable* _Nullable error);

/**
 * NewHashFromHex converts a hex string to a hash value.
 */
FOUNDATION_EXPORT GprobeHash* _Nullable GprobeNewHashFromHex(NSString* _Nullable hex, NSError* _Nullable* _Nullable error);

/**
 * NewHashes creates a slice of uninitialized Hashes.
 */
FOUNDATION_EXPORT GprobeHashes* _Nullable GprobeNewHashes(long size);

/**
 * NewHashesEmpty creates an empty slice of Hashes values.
 */
FOUNDATION_EXPORT GprobeHashes* _Nullable GprobeNewHashesEmpty(void);

/**
 * NewHeaderFromJSON parses a header from a JSON data dump.
 */
FOUNDATION_EXPORT GprobeHeader* _Nullable GprobeNewHeaderFromJSON(NSString* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewHeaderFromRLP parses a header from an RLP data dump.
 */
FOUNDATION_EXPORT GprobeHeader* _Nullable GprobeNewHeaderFromRLP(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewInterface creates a new empty interface that can be used to pass around
generic types.
 */
FOUNDATION_EXPORT GprobeInterface* _Nullable GprobeNewInterface(void);

/**
 * NewInterfaces creates a slice of uninitialized interfaces.
 */
FOUNDATION_EXPORT GprobeInterfaces* _Nullable GprobeNewInterfaces(long size);

/**
 * NewKeyStore creates a keystore for the given directory.
 */
FOUNDATION_EXPORT GprobeKeyStore* _Nullable GprobeNewKeyStore(NSString* _Nullable keydir, long scryptN, long scryptP);

// skipped function NewKeyedTransactOpts with unsupported parameter or return types


/**
 * NewNode creates and configures a new Gprobe node.
 */
FOUNDATION_EXPORT GprobeNode* _Nullable GprobeNewNode(NSString* _Nullable datadir, GprobeNodeConfig* _Nullable config, NSError* _Nullable* _Nullable error);

/**
 * NewNodeConfig creates a new node option set, initialized to the default values.
 */
FOUNDATION_EXPORT GprobeNodeConfig* _Nullable GprobeNewNodeConfig(void);

/**
 * NewProbeumClient connects a client to the given URL.
 */
FOUNDATION_EXPORT GprobeProbeumClient* _Nullable GprobeNewProbeumClient(NSString* _Nullable rawurl, NSError* _Nullable* _Nullable error);

/**
 * NewReceiptFromJSON parses a transaction receipt from a JSON data dump.
 */
FOUNDATION_EXPORT GprobeReceipt* _Nullable GprobeNewReceiptFromJSON(NSString* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewReceiptFromRLP parses a transaction receipt from an RLP data dump.
 */
FOUNDATION_EXPORT GprobeReceipt* _Nullable GprobeNewReceiptFromRLP(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewSmartLightNode creates and configures a SmartLight node.
It runs a LES light client underneath with SmartLight services on top.
 */
FOUNDATION_EXPORT GprobeSmartLightNode* _Nullable GprobeNewSmartLightNode(NSString* _Nullable datadir, GprobeSmartLightNodeConfig* _Nullable config, NSError* _Nullable* _Nullable error);

/**
 * NewSmartLightNodeConfig creates a new SmartLight node config with defaults.
 */
FOUNDATION_EXPORT GprobeSmartLightNodeConfig* _Nullable GprobeNewSmartLightNodeConfig(void);

/**
 * NewTopics creates a slice of uninitialized Topics.
 */
FOUNDATION_EXPORT GprobeTopics* _Nullable GprobeNewTopics(long size);

/**
 * NewTopicsEmpty creates an empty slice of Topics values.
 */
FOUNDATION_EXPORT GprobeTopics* _Nullable GprobeNewTopicsEmpty(void);

/**
 * NewTransactOpts creates a new option set for contract transaction.
 */
FOUNDATION_EXPORT GprobeTransactOpts* _Nullable GprobeNewTransactOpts(void);

/**
 * NewTransaction creates a new transaction with the given properties. Contracts
can be created by transacting with a nil recipient.
 */
FOUNDATION_EXPORT GprobeTransaction* _Nullable GprobeNewTransaction(int64_t nonce, GprobeAddress* _Nullable to, GprobeBigInt* _Nullable amount, int64_t gasLimit, GprobeBigInt* _Nullable gasPrice, NSData* _Nullable data);

/**
 * NewTransactionFromJSON parses a transaction from a JSON data dump.
 */
FOUNDATION_EXPORT GprobeTransaction* _Nullable GprobeNewTransactionFromJSON(NSString* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * NewTransactionFromRLP parses a transaction from an RLP data dump.
 */
FOUNDATION_EXPORT GprobeTransaction* _Nullable GprobeNewTransactionFromRLP(NSData* _Nullable data, NSError* _Nullable* _Nullable error);

/**
 * PubkeyToProbeAddress derives a ProbeChain address from a raw Dilithium public key.
 */
FOUNDATION_EXPORT NSString* _Nonnull GprobePubkeyToProbeAddress(NSData* _Nullable pubKeyBytes, NSError* _Nullable* _Nullable error);

/**
 * SetVerbosity sets the global verbosity level (between 0 and 6 - see logger/verbosity.go).
 */
FOUNDATION_EXPORT void GprobeSetVerbosity(long level);

/**
 * SmartLightRewardPerBlock returns the per-block reward pool (in wei).
 */
FOUNDATION_EXPORT NSString* _Nonnull GprobeSmartLightRewardPerBlock(void);

/**
 * SmartLightStakeRequired returns the minimum PROBE stake (in wei) to register.
 */
FOUNDATION_EXPORT NSString* _Nonnull GprobeSmartLightStakeRequired(void);

/**
 * VerifySignature verifies a Dilithium signature.
 */
FOUNDATION_EXPORT BOOL GprobeVerifyDilithiumSignature(NSString* _Nullable pubKeyHex, NSData* _Nullable message, NSData* _Nullable signature, BOOL* _Nullable ret0_, NSError* _Nullable* _Nullable error);

@class GprobeFilterLogsHandler;

@class GprobeNewHeadHandler;

@class GprobeSigner;

/**
 * FilterLogsHandler is a client-side subscription callback to invoke on events and
subscription failure.
 */
@interface GprobeFilterLogsHandler : NSObject <goSeqRefInterface, GprobeFilterLogsHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(NSString* _Nullable)failure;
- (void)onFilterLogs:(GprobeLog* _Nullable)log;
@end

/**
 * NewHeadHandler is a client-side subscription callback to invoke on events and
subscription failure.
 */
@interface GprobeNewHeadHandler : NSObject <goSeqRefInterface, GprobeNewHeadHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(NSString* _Nullable)failure;
- (void)onNewHead:(GprobeHeader* _Nullable)header;
@end

/**
 * Signer is an interface defining the callback when a contract requires a
method to sign the transaction before submission.
 */
@interface GprobeSigner : NSObject <goSeqRefInterface, GprobeSigner> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (GprobeTransaction* _Nullable)sign:(GprobeAddress* _Nullable)addr unsignedTx:(GprobeTransaction* _Nullable)unsignedTx error:(NSError* _Nullable* _Nullable)error;
@end

#endif
