package contracts

import (
	"encoding/hex"
	"math/big"
)

// Contract bytecodes — compiled from Solidity sources.
// These must be generated by compiling the actual contracts.
// For now, we provide a placeholder mechanism that loads from files or embeds.

// NOTE: These bytecodes need to be populated by running:
//   solc --optimize --bin contracts/ERC20Template.sol
// Then pasting the hex output here.
// When bytecodes are not available, the test framework will report SKIP for deploy tests.

// mustDecodeHex decodes hex or panics.
func mustDecodeHex(s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil {
		panic("invalid bytecode hex: " + err.Error())
	}
	return b
}

// ERC20TemplateBytecode is the compiled creation bytecode for ERC20Template.sol
// Compiled with solc 0.6.6, optimizer enabled, 200 runs
var ERC20TemplateBytecode []byte

// WPROBEBytecode is the compiled creation bytecode for WPROBE.sol
var WPROBEBytecode []byte

// IdentityRegistryBytecode is the compiled creation bytecode for IdentityRegistry.sol
var IdentityRegistryBytecode []byte

// KeyTradingBytecode is the compiled creation bytecode for KeyTrading.sol
var KeyTradingBytecode []byte

// ProSwapFactoryBytecode is the compiled creation bytecode for ProSwapFactory.sol
var ProSwapFactoryBytecode []byte

// ProSwapRouter02Bytecode is the compiled creation bytecode for ProSwapRouter02.sol
var ProSwapRouter02Bytecode []byte

// ProSwapPairBytecode is the compiled creation bytecode for ProSwapPair.sol
var ProSwapPairBytecode []byte

// MasterChefBytecode is the compiled creation bytecode for MasterChef.sol
var MasterChefBytecode []byte

// PredictionMarketBytecode is the compiled creation bytecode for PredictionMarket.sol
var PredictionMarketBytecode []byte

// ExchangeSettlementBytecode is the compiled creation bytecode for ExchangeSettlement.sol
var ExchangeSettlementBytecode []byte

// ProSwapTokenBytecode for the PST reward token
var ProSwapTokenBytecode []byte

// EncodeERC20Constructor encodes constructor args for ERC20Template.
// constructor(string _name, string _symbol, uint8 _decimals, uint256 _initialSupply)
func EncodeERC20Constructor(name, symbol string, decimals uint8, initialSupply *big.Int) []byte {
	// ABI encode: 4 dynamic/static params
	// offset_name (32) | offset_symbol (32) | decimals (32) | initialSupply (32) | name_data | symbol_data

	nameBytes := []byte(name)
	symbolBytes := []byte(symbol)

	namePadded := len(nameBytes)
	if namePadded%32 != 0 {
		namePadded += 32 - (namePadded % 32)
	}
	symbolPadded := len(symbolBytes)
	if symbolPadded%32 != 0 {
		symbolPadded += 32 - (symbolPadded % 32)
	}

	// Fixed params first, then dynamic data
	// Param layout: [offset_name, offset_symbol, decimals, initialSupply, name_len, name_data, symbol_len, symbol_data]
	// offset_name = 4*32 = 128 (after 4 fixed-size slots)
	// offset_symbol = 128 + 32 + namePadded

	offsetName := big.NewInt(int64(4 * 32))
	offsetSymbol := big.NewInt(int64(4*32 + 32 + namePadded))

	var result []byte
	result = append(result, EncodeUint256(offsetName)...)
	result = append(result, EncodeUint256(offsetSymbol)...)
	result = append(result, EncodeUint256(big.NewInt(int64(decimals)))...)
	result = append(result, EncodeUint256(initialSupply)...)

	// Name
	result = append(result, EncodeUint256(big.NewInt(int64(len(nameBytes))))...)
	padName := make([]byte, namePadded)
	copy(padName, nameBytes)
	result = append(result, padName...)

	// Symbol
	result = append(result, EncodeUint256(big.NewInt(int64(len(symbolBytes))))...)
	padSymbol := make([]byte, symbolPadded)
	copy(padSymbol, symbolBytes)
	result = append(result, padSymbol...)

	return result
}

// BytecodesAvailable returns true if contract bytecodes have been loaded.
func BytecodesAvailable() bool {
	return len(ERC20TemplateBytecode) > 0
}

// LoadBytecodesFromCompiled loads bytecodes from solc output files.
// This should be called during initialization after contracts are compiled.
func LoadBytecodesFromCompiled(dir string) error {
	// TODO: Load from .bin files produced by solc
	// For now, contracts need to be compiled externally and bytecodes set via init()
	return nil
}
