
// Objective-C API for talking to the following Go packages
//
//	github.com/probechain/go-probe/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gprobe_FRAMEWORK_H__
#define __Gprobe_FRAMEWORK_H__

#include "Gprobe.objc.h"
#include "Universe.objc.h"

#endif
